#!/bin/bash
#
# test add functionality for git plugin
# 
# @author <bprinty@gmail.com>
# ------------------------------------------------

# simple
create add-test
git xfer add add-test
assertContains "$CACHE" "add-test"
git xfer rm add-test
assertNotContains "$CACHE" "add-test"

# space
create add-test\ with\ space
git xfer add add-test\ with\ space
assertContains "$CACHE" 'add-test with space'
git xfer rm add-test\ with\ space
assertNotContains "$CACHE" 'add-test with space'

# directory with space
create space\ dir/add-test\ with\ space
git xfer add space\ dir/add-test\ with\ space
assertContains "$CACHE" 'space dir/add-test with space'
git xfer rm space\ dir/add-test\ with\ space
assertNotContains "$CACHE" 'space dir/add-test with space'
