#!/bin/bash
#
# test add functionality for git plugin
# 
# @author <bprinty@gmail.com>
# ------------------------------------------------

# usage
printf 'add usage ..................... '
assertEqual 4 `git xfer add | wc -l`
echo ''

# add
printf 'add ........................... '
create add-test
git xfer add add-test
assertContains "$CACHE" "add-test"
git xfer rm add-test
assertNotContains "$CACHE" "add-test"
echo ''

# space
printf 'with space ..................... '
create add-test\ with\ space
git xfer add add-test\ with\ space
assertContains "$CACHE" 'add-test\\ with\\ space'
git xfer rm add-test\ with\ space
assertNotContains "$CACHE" 'add-test\\ with\\ space'
echo ''

# directory with space
printf 'directory with space ........... '
create space\ dir/add-test\ with\ space
git xfer add space\ dir/add-test\ with\ space
assertContains "$CACHE" 'space\\ dir/add-test\\ with\\ space'
git xfer rm space\ dir/add-test\ with\ space
assertNotContains "$CACHE" 'space\\ dir/add-test\\ with\\ space'
echo ''
