#!/bin/bash
#
# test add functionality for git plugin
# 
# @author <bprinty@gmail.com>
# ------------------------------------------------

# usage
printf 'list usage .................... '
assertEqual 4 `git xfer add | wc -l`
echo ''

# list
printf 'list ........................... '
create add-test
create space\ dir/add-test\ with\ space
git xfer add add-test space\ dir/add-test\ with\ space
# git xfer list testtttt
echo ''