#!/bin/bash
#
# test usage strings for git plugin
# 
# @author <bprinty@gmail.com>
# ------------------------------------------------

assertEqual 4 `git xfer add | wc -l`
assertEqual 4 `git xfer remove | wc -l`
assertEqual 4 `git xfer rm | wc -l`
assertEqual 4 `git xfer list -h | wc -l`
assertEqual 4 `git xfer archive | wc -l`
assertEqual 5 `git xfer sync | wc -l`
assertEqual 5 `git xfer diff | wc -l`
assertEqual 5 `git xfer push | wc -l`
assertEqual 5 `git xfer pull | wc -l`

