#!/bin/bash
#
# test push functionality for git plugin
# 
# @author <bprinty@gmail.com>
# ------------------------------------------------

# push
create add-test
create add-test\ with\ space
create space\ dir/add-test\ with\ space
git xfer add add-test
git xfer add add-test\ with\ space
git xfer add space\ dir/add-test\ with\ space
assertEqual 3 `git xfer list | wc -l`
assertEqual 3 `git xfer diff testserver 2>/dev/null | grep '<' | wc -l`
assertEqual 0 `git xfer diff testserver 2>/dev/null | grep '>' | wc -l`
git xfer push testserver &>/dev/null
cd "$REMOTE_SANDBOX"
assertExists "add-test"
assertContains "$REMOTE_CACHE" "add-test"
assertExists "add-test with space"
assertContains "$REMOTE_CACHE" "add-test with space"
assertExists "space dir/add-test with space"
assertContains "$REMOTE_CACHE" "space dir/add-test with space"

# more
cd "$SANDBOX"
create add-test-two
git xfer add add-test-two
assertEqual 4 `git xfer list | wc -l`
assertEqual 1 `git xfer diff testserver 2>/dev/null | grep '<' | wc -l`
assertEqual 0 `git xfer diff testserver 2>/dev/null | grep '>' | wc -l`
git xfer push testserver &>/dev/null
cd "$REMOTE_SANDBOX"
assertExists "add-test-two"
assertContains "$REMOTE_CACHE" "add-test-two"