#!/usr/bin/env sh
#
# test add functionality for git plugin
# 
# @author <bprinty@gmail.com>
# ------------------------------------------------


# config
# ------
base=`git rev-parse --show-toplevel`
cache="$base/.git/xfer/cache"
cd "$base/test"
testdir=/tmp/git-xfer-testing-remote
rm "$cache"
touch "$cache"
mkdir -p "$testdir"
cp -r "$base" "$testdir/"
if [ ! `git remote | grep "testserver"` ]; then
    git remote add testserver ssh://$USER@localhost:2222$testdir/git-xfer
fi
git xfer --reset


# funcs
# -----
clean() {
    cd "$base/test"
    if [ `git branch | grep 'testing' | wc -l` -eq 1 ]; then
        git branch -d testing
    fi
    rm -f test-local-file test-remote-file
    git remote rm testserver
    rm -rf "$testdir"
    rm "$cache"
    touch "$cache"
}

create() {
    dir=`dirname "$1"`
    mkdir -p "$dir"
    echo "$1" > "$1"
}


# testing
# -------
# sync
printf 'sync .......................... '
cd "$testdir"/git-xfer/
git branch testing
git checkout testing
cd "$base/test"
git branch | grep 'master'
git xfer sync testserver master
cd "$testdir"/git-xfer/test
if [ `git branch | grep 'master' | wc -l` -ne 1 ]; then
    echo 'Sync failed!';
    clean
    exit 1
fi
printf 'ok\n'

# push
printf 'push .......................... '
cd "$base/test"
create test-local-file
create test-file\ withspace
create space\ test/test-file
git xfer add test-local-file test-file\ withspace space\ test/test-file
git xfer push testserver
cd "$testdir"/git-xfer/test
if [ ! -e "test-local-file" ]; then
    echo "Fail! Cannot push files to remote."
    clean
    exit 1
fi
if [ ! -e "test-file withspace" ]; then
    echo "Fail! Cannot push files to remote."
    clean
    exit 1
fi
if [ ! -e "space test/test-file" ]; then
    echo "Fail! Cannot push files to remote."
    clean
    exit 1
fi
if [ `git xfer list | grep "test-local-file" | wc -l` -ne 1 ]; then
    echo "Fail! Remote not synced."
    clean
    exit 1
fi
if [ `git xfer list | grep "withspace" | wc -l` -ne 1 ]; then
    echo "Fail! Remote not synced."
    clean
    exit 1
fi
if [ `git xfer list | grep "space.*test-file" | wc -l` -ne 1 ]; then
    echo "Fail! Remote not synced."
    clean
    exit 1
fi
git xfer rm test-local-file test-file\ withspace space\ test/test-file
cd "$base/test"
git xfer rm test-local-file test-file\ withspace space\ test/test-file
rm -rf space\ test
printf 'ok\n'

# pull
printf 'pull .......................... '
cd "$testdir/git-xfer/test"
create test-remote-file
create test-file\ withspace
create space\ test/test-file
git xfer add test-remote-file test-file\ withspace space\ test/test-file
cd "$base/test"
git xfer pull testserver
if [ ! -e "test-remote-file" ]; then
    echo "Fail! Cannot push files to remote."
    clean
    exit 1
fi
if [ ! -e "test-file withspace" ]; then
    echo "Fail! Cannot push files to remote."
    clean
    exit 1
fi
if [ ! -e "space test/test-file" ]; then
    echo "Fail! Cannot push files to remote."
    clean
    exit 1
fi
if [ `git xfer list | grep "test-remote-file" | wc -l` -ne 1 ]; then
    echo "Fail! Local not synced."
    clean
    exit 1
fi
if [ `git xfer list | grep "withspace" | wc -l` -ne 1 ]; then
    echo "Fail! Local not synced."
    clean
    exit 1
fi
if [ `git xfer list | grep "space.*test-file" | wc -l` -ne 1 ]; then
    echo "Fail! Local not synced."
    clean
    exit 1
fi
git xfer rm test-remote-file test-file\ withspace space\ test/test-file
rm -rf space\ test
printf 'ok\n'

echo -n 'clean ......................... '
clean
echo 'ok'