#!/usr/bin/env sh
#
# test add functionality for git plugin
# 
# @author <bprinty@gmail.com>
# ------------------------------------------------

# add
printf 'add ........................... '
create add-test
git xfer add add-test
shasum=`getShasum add-test`
cat "$cache"
assertContains "$cache" "$shasum"
git xfer rm add-test
assertNotContains "$cache" "$shasum"

# printf 'add with space ................ '
# create add-withspace\ test
# git xfer add add-withspace\ test
# if [ `cat "$cache" | grep "add-withspace" | wc -l` -ne 1 ]; then
#     echo 'Fail! Error adding files.'
#     clean
#     exit 1
# fi
# git xfer rm add-withspace\ test
# printf 'ok\n'

# printf 'add with space ................ '
# create space\ test/test-add-spacedir
# git xfer add space\ test
# if [ `cat "$cache" | grep "test-add-spacedir" | wc -l` -ne 1 ]; then
#     echo 'Fail! Error adding files.'
#     clean
#     exit 1
# fi
# git xfer rm space\ test
# rm -rf space\ test
# printf 'ok\n'

# # add without gitignore
# create gitignore-test
# git xfer add --no-ignore gitignore-test
# printf 'add no-ignore ................. '
# if [ `cat "$base/.gitignore" | grep "test-gtignore" | wc -l` -ne 0 ]; then
#     echo 'Fail! Error adding files without ignore.'
#     clean
#     exit 1
# fi
# git xfer rm gitignore-test
# printf 'ok\n'