#!/usr/bin/env sh
#
# test add functionality for git plugin
# 
# @author <bprinty@gmail.com>
# ------------------------------------------------


# config
# ------
base=`git rev-parse --show-toplevel`
cache="$base/.git/xfer/cache"
cd "$base/test"
testdir=/tmp/git-xfer-testing-remote
rm "$cache"
touch "$cache"
mkdir -p "$testdir"
cp -r "$base" "$testdir/"
if [ ! `git remote | grep "testserver"` ]; then
    git remote add testserver ssh://$USER@localhost:2222$testdir/git-xfer
fi


# funcs
# -----
clean() {
    cd "$base/test"
    if [ `git branch | grep 'testing' | wc -l` -eq 1 ]; then
        git branch -d testing
    fi
    rm -f test-local-file test-remote-file
    git remote remove testserver
    rm -rf "$testdir"
    rm "$cache"
    touch "$cache"
}


# testing
# -------
echo -n 'sync .......................... '
cd "$testdir"/git-xfer/
git branch testing
git checkout testing
cd "$base/test"
git xfer sync testserver master
cd "$testdir"/git-xfer/test
if [ `git branch | grep '* master' | wc -l` -ne 1 ]; then
    echo 'Sync failed!';
    clean
    exit 1
fi
echo 'ok'

# push
echo -n 'push .......................... '
cd "$base/test"
mkdir -p space\ test
echo 'test' > test-local-file
echo 'test' > test-file\ withspace
echo 'test' > space\ test/test-file
git xfer add test-local-file test-file\ withspace space\ test/test-file
git xfer push testserver
cd "$testdir"/git-xfer/test
if [ ! -e "test-local-file" ]; then
    echo "Fail! Cannot push files to remote."
    clean
    exit 1
fi
if [ ! -e "test-file withspace" ]; then
    echo "Fail! Cannot push files to remote."
    clean
    exit 1
fi
if [ ! -e "space test/test-file" ]; then
    echo "Fail! Cannot push files to remote."
    clean
    exit 1
fi
if [ `git xfer list | grep "test-local-file" | wc -l` -ne 1 ]; then
    echo "Fail! Remote not synced."
    clean
    exit 1
fi
if [ `git xfer list | grep "withspace" | wc -l` -ne 1 ]; then
    echo "Fail! Remote not synced."
    clean
    exit 1
fi
if [ `git xfer list | grep "space.*test-file" | wc -l` -ne 1 ]; then
    echo "Fail! Remote not synced."
    clean
    exit 1
fi
git xfer rm test-local-file test-file\ withspace space\ test/test-file
cd "$base/test"
git xfer rm test-local-file test-file\ withspace space\ test/test-file
rm -rf space\ test
printf 'ok\n'

# pull
echo 'pull .......................... '
cd "$testdir/git-xfer/test"
mkdir -p space\ test
echo 'test' > test-remote-file
echo 'test' > test-file\ withspace
echo 'test' > space\ test/test-file
git xfer add test-remote-file test-file\ withspace space\ test/test-file
cd "$base/test"
git xfer pull testserver
if [ ! -e "test-remote-file" ]; then
    echo "Fail! Cannot push files to remote."
    clean
    exit 1
fi
if [ ! -e "test-file withspace" ]; then
    echo "Fail! Cannot push files to remote."
    clean
    exit 1
fi
if [ ! -e "space test/test-file" ]; then
    echo "Fail! Cannot push files to remote."
    clean
    exit 1
fi
if [ `git xfer list | grep "test-remote-file" | wc -l` -ne 1 ]; then
    echo "Fail! Local not synced."
    clean
    exit 1
fi
if [ `git xfer list | grep "withspace" | wc -l` -ne 1 ]; then
    echo "Fail! Local not synced."
    clean
    exit 1
fi
if [ `git xfer list | grep "space.*test-file" | wc -l` -ne 1 ]; then
    echo "Fail! Local not synced."
    clean
    exit 1
fi
git xfer rm test-remote-file test-file\ withspace space\ test/test-file
rm -rf space\ test
printf 'ok\n'

echo -n 'clean ......................... '
clean
echo 'ok'