#!/bin/bash
#
# test add functionality for git plugin
# 
# @author <bprinty@gmail.com>
# ------------------------------------------------


# list
create add-test
create space\ dir/add-test\ with\ space
git xfer add add-test space\ dir/add-test\ with\ space
assertEqual 2 `git xfer list | wc -l`
git xfer rm add-test space\ dir/add-test\ with\ space
