#!/bin/bash
#
# test add functionality for git plugin
# 
# @author <bprinty@gmail.com>
# ------------------------------------------------

assertEqual 4 `git xfer add | wc -l`
assertEqual 4 `git xfer remove | wc -l`
assertEqual 4 `git xfer rm | wc -l`
assertEqual 4 `git xfer list -h | wc -l`

