#!/bin/bash
#
# wrapper script for test management
#
# @author <bprinty@gmail.com>
# --------------------------------------


# init
# ----
CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BASE=`git rev-parse --show-toplevel`
CACHE="$BASE/.git/xfer/cache"
TSANDBOX="$CWD/sandbox"


# funcs
# -----
usage() {
    echo ""
    echo "Usage: test <name> [<type>]"
    echo ""
    echo "Arguments:"
    echo "  <name>       Name of test to perform."
    echo ""
    echo "Optional Arguments:"
    echo "  <type>       Remote type to test (local|remote)" 
    echo ""
    exit 1
}

clean() {
    # remove testing files
    # rm -rf $TSANDBOX

    # clear remotes and branches
    if [ `git remote | grep 'testserver' | wc -l` -eq 1 ]; then
        git remote rm testserver
    fi
    if [ `git branch | grep 'testing' | wc -l` -eq 1 ]; then
        git branch -d testing
    fi

    # clear cache
    rm -rf "$CACHE"
    touch "$CACHE"
}

create() {
    dir=`dirname "$1"`
    if [ "$dir" == "." ]; then
        
    mkdir -p "$dir"
    echo "$1" > "$1"
}

FAIL='FALSE'
assertEqual() {
    GREEN='\033[0;32m'
    RED='\033[0;31m'
    NC='\033[0m'
    if [ "$1" == "$2" ]; then
        printf $GREEN'✓'$NC
    else
        printf $RED'✗'$NC
        FAIL='TRUE'
    fi
}

assertContains() {
    GREEN='\033[0;32m'
    RED='\033[0;31m'
    NC='\033[0m'
    if [ `cat "$1" | grep "$2" | wc -l` -gt 0 ]; then
        printf $GREEN'✓'$NC
    else
        printf $RED'✗'$NC
        FAIL='TRUE'
    fi
}

assertNotContains() {
    GREEN='\033[0;32m'
    RED='\033[0;31m'
    NC='\033[0m'
    if [ `cat "$1" | grep "$2" | wc -l` -gt 0 ]; then
        printf $RED'✗'$NC
        FAIL='TRUE'
    else
        printf $GREEN'✓'$NC
    fi
}

getShasum() {
    if [ `uname` = "Darwin" ]; then
        shasum=`shasum "$1" | awk '{ print $1 }'`
    else
        shasum=`sha1sum "$1" | awk '{ print $1 }'`
    fi
    echo $shasum
}


# test
# ----
if [ $# -eq 0 ]; then
    usage
fi

if [ ! -z $2 ]; then
    if [ -e "$CWD/config/$2" ]; then
        source "$CWD/config/$2"
    fi
fi

if [ -e "$CWD/test-$1" ]; then
    mkdir -p "$TSANDBOX"
    pushd "$TSANDBOX"
    source "$CWD/test-$1"
    popd
fi


# clean
# -----
clean