#!/usr/bin/env sh
#
# test add functionality for git plugin
# 
# @author <bprinty@gmail.com>
# ------------------------------------------------


# config
# ------
base=`git rev-parse --show-toplevel`
cache="$base/.git/xfer/cache"
cd "$base/test"
testdir=/tmp/git-xfer-testing-local
rm "$cache"
touch "$cache"
mkdir -p "$testdir"
cp -r "$base" "$testdir/"
if [ ! `git remote | grep "testserver"` ]; then
    git remote add testserver "$testdir/git-xfer"
fi


# funcs
# -----
clean() {
    cd "$base/test"
    rm -f test-local-file test-remote-file
    git remote remove testserver
    rm -rf "$testdir"
    rm "$cache"
    touch "$cache"
}


# testing
# -------
# add
git xfer add test-local test-remote
shasum=`sha1sum test-local | awk '{ print $1 }'`
if [ `cat "$cache" | grep "$shasum" | wc -l` -ne 1 ]; then
    echo 'Fail! Error adding files.'
    exit 1
fi
if [ `cat "$cache" | wc -l` -ne 2 ]; then
    echo 'Fail! Error adding files.'
    exit 1
fi

# list
if [ `git xfer list | wc -l` -ne 2 ]; then
    echo 'Fail! Error listing files.'
    exit 1
fi
git xfer list -v > "$cache.tst"
if [ `diff "$cache.tst" "$cache" | wc -l` -ne 0 ]; then
    echo 'Fail! Error listing verbose.'
    rm "$cache.tst"
    exit 1
fi
rm "$cache.tst"

# remove
git xfer remove test-local test-remote
if [ `cat "$cache" | wc -l` -ne 0 ]; then
    echo 'Fail! Error removing files.'
    exit 1
fi

# push
echo 'test' > test-local-file
git xfer add test-local-file
git xfer push testserver
cd "$testdir"/git-xfer/test
if [ ! -e "test-local-file" ]; then
    echo "Fail! Cannot push files to remote."
    clean
    exit 1
fi
if [ `git xfer list | grep "test-local-file" | wc -l` -ne 1 ]; then
    echo "Fail! Remote not synced."
    clean
    exit 1
fi
cd "$base/test"
if [ `git xfer list | grep "test-local-file" | grep "testserver" | wc -l` -ne 1 ]; then
    echo "Fail! Local not synced with transfer status."
    clean
    exit 1
fi

# pull
cd "$testdir/git-xfer/test"
echo 'test' > test-remote-file
git xfer add test-remote-file
cd "$base/test"
git xfer pull testserver
if [ ! -e "test-remote-file" ]; then
    echo "Fail! Cannot pull remote files."
    clean
    exit 1
fi
if [ `git xfer list | grep "test-remote-file" | wc -l` -ne 1 ]; then
    echo "Fail! Local not synced."
    clean
    exit 1
fi
git xfer rm test-local-file
git xfer rm test-remote-file

clean